version: '3.3'

services:
    # postgres
    postgres:
        container_name: 'uerj.projeto_final.postgres'
        image: postgres:11.1
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=tpch
        volumes:
            - ./bin:/app/bin
            - ./resources:/app/resources
        working_dir: /app

    # db admin
    adminer:
        container_name: 'uerj.projeto_final.adminer'
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - postgres
        links:
            - postgres
