version: '3.3'

services:
    # gradle
    gradle:
        container_name: 'uerj.projeto_final.gradle'
        image: gradle:5.6.2-jdk8
        volumes:
            - ./:/app
        working_dir: /app
        depends_on:
            - postgres
            - mongo
        links:
            - postgres
            - mongo

    # postgres
    postgres:
        container_name: 'uerj.projeto_final.postgres'
        image: postgres:11.1
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=tpch
        volumes:
            - ./bin:/app/bin
            - ./resources:/app/resources
        working_dir: /app
        shm_size: 2gb

    # db admin
    adminer:
        container_name: 'uerj.projeto_final.adminer'
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - postgres
        links:
            - postgres

    # mongo
    mongo:
        container_name: 'uerj.projeto_final.mongo'
        image: mongo:3.6.9
        ports:
            - 27017:27017
        volumes:
            - ./docker/mongo/mongod.conf:/etc/mongod.conf
            - ./resources:/app/resources
        working_dir: /app
        entrypoint: ["mongod", "--config", "/etc/mongod.conf", "--noIndexBuildRetry"]

    # mongo-express
    mongo-express:
        container_name: 'uerj.projeto_final.mongo_express'
        image: mongo-express
        ports:
            - 8081:8081
        depends_on:
            - mongo
        links:
            - mongo
